//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Osada.player
{
    public class Player
    {
        public int PlayerId { get; set; }
        // 0 - Food, 1 - Gold, 2 - Rock, 3 - Wood
        public int[] Resource { get; set; }
        public int Food { get; set; }
        public int Gold { get; set; }
        public int Rock { get; set; }
        public int Wood { get; set; }
        public int Sciencists { get; set; }
        public int SciencistsAll { get; set; }
        public int Soldiers { get; set; }
        public int SoldiersAll { get; set; }
        public int Settlers { get; set; }
        public int SettlersMax { get; set; }
        public int SettlersAll { get; set; }
        public int[] Technology { get; set; }
        public Player(int getPlayerId)
        {
            PlayerId = getPlayerId;
            Food = Gold = Rock = Wood = 100;
            Sciencists = SciencistsAll = Soldiers = SoldiersAll = 0;
            Resource = new int[]
            {
                100, // 0
                100, // 1
                100, // 2
                100  // 3
            };
            Technology = new int[] {1,1,1,1};
            Settlers = SettlersAll = 5;
            SettlersMax = 10;
        }
    }
}